workflow fix

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -8,7 +8,7 @@ on:
     branches:
       - '*'
 
-#This workflow compiles the maven project and executes tests that check for code correction and coverage, to be deployed to a github package
+# This workflow compiles the maven project and executes tests that check for code correction and coverage, to be deployed to a github package
 
 jobs:
   build:
@@ -20,7 +20,7 @@ jobs:
     steps:
     - uses: actions/checkout@v4
 
-    #Set up the JDK environment
+    # Set up the JDK environment
     - name: Set up JDK 19
       uses: actions/setup-java@v4
       with:
@@ -29,40 +29,39 @@ jobs:
         server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
         settings-path: ${{ github.workspace }} # location for the settings.xml file
 
-    #Compiles the project
+    # Compiles the project
     - name: Compile Source Code
       run: mvn compile
 
-    #Executes the project's tests
+    # Executes the project's tests
     - name: Execute Unit Tests
       run: mvn test
 
-    #Checks what is the code coverage according to jacoco
+    # Checks what is the code coverage according to jacoco
     - name: Verify Code Coverage
       id: coverage
       run: |
-      mvn verify
-      mvn jacoco:report
-      REPORT=$(mvn jacoco:report)
-      echo "JaCoCo Report: $REPORT"
-      COVERAGE=$(echo "$REPORT" | grep -oP 'Total.*?\K\d{1,3}(?=%)')
-      if [ -z "$COVERAGE" ]; then
-        echo "Failed to extract coverage percentage from JaCoCo report."
-        exit 1
-      fi
-      echo "Code coverage is $COVERAGE%"
-      echo "coverage=$COVERAGE" >> $GITHUB_ENV
-      echo "$COVERAGE" > coverage.txt
+        mvn verify
+        mvn jacoco:report
+        REPORT=$(mvn jacoco:report)
+        echo "JaCoCo Report: $REPORT"
+        COVERAGE=$(echo "$REPORT" | grep -oP 'Total.*?\K\d{1,3}(?=%)')
+        if [ -z "$COVERAGE" ]; then
+          echo "Failed to extract coverage percentage from JaCoCo report."
+          exit 1
+        fi
+        echo "Code coverage is $COVERAGE%"
+        echo "coverage=$COVERAGE" >> $GITHUB_ENV
+        echo "$COVERAGE" > coverage.txt
 
-
-    #If the branch is main, the previous steps went well, and the coverage is acceptable, the code is deployed as a github package
+    # If the branch is main, the previous steps went well, and the coverage is acceptable, the code is deployed as a github package
     - name: Deploy Snapshot to GitHub Packages
       if: github.ref == 'refs/heads/main' && env.coverage >= 80 && success()
       run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/inestrivino/JavaPandas
       env:
         GITHUB_TOKEN: ${{ github.token }}
-    
-    #We upload a report of the coverage to be used by the docker workflow
+
+    # We upload a report of the coverage to be used by the docker workflow
     - name: Upload Coverage Report
       uses: actions/upload-artifact@v4
       with:
