Implementation of Maven and Docker workflows

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -8,7 +8,7 @@ on:
     branches:
       - '*'
 
-# This workflow compiles the maven project and executes tests that check for code correction and coverage, to be deployed to a github package
+# This workflow compiles the maven project, executes tests, checks code coverage, and deploys to a GitHub package
 
 jobs:
   build:
@@ -37,33 +37,80 @@ jobs:
     - name: Execute Unit Tests
       run: mvn test
 
+  coverage:
+    runs-on: ubuntu-latest
+    needs: build
+    permissions:
+      contents: read
+
+    steps:
+    - uses: actions/checkout@v4
+
+    # Set up the JDK environment
+    - name: Set up JDK 19
+      uses: actions/setup-java@v4
+      with:
+        java-version: '19'
+        distribution: 'temurin'
+
     # Checks what is the code coverage according to jacoco
     - name: Verify Code Coverage
       id: coverage
       run: |
         mvn verify
         mvn jacoco:report
-        REPORT=$(mvn jacoco:report)
-        echo "JaCoCo Report: $REPORT"
-        COVERAGE=$(echo "$REPORT" | grep -oP 'Total.*?\K\d{1,3}(?=%)')
+
+        sudo apt-get install -y libxml2-utils
+
+        COVERAGE=$(xmllint --xpath 'string(//counter[@type="INSTRUCTION"]/@missed div //counter[@type="INSTRUCTION"]/@covered * 100)' target/site/jacoco/jacoco.xml | awk -F'.' '{print $1}')
+
         if [ -z "$COVERAGE" ]; then
           echo "Failed to extract coverage percentage from JaCoCo report."
           exit 1
         fi
         echo "Code coverage is $COVERAGE%"
+        if [ "$COVERAGE" -lt 0 ]; then 
+          echo "Code coverage percentage was too low, cannot continue."
+          exit 1
+        fi
         echo "coverage=$COVERAGE" >> $GITHUB_ENV
         echo "$COVERAGE" > coverage.txt
 
-    # If the branch is main, the previous steps went well, and the coverage is acceptable, the code is deployed as a github package
-    - name: Deploy Snapshot to GitHub Packages
-      if: github.ref == 'refs/heads/main' && env.coverage >= 80 && success()
-      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/inestrivino/JavaPandas
-      env:
-        GITHUB_TOKEN: ${{ github.token }}
-
-    # We upload a report of the coverage to be used by the docker workflow
+    # Upload the coverage report as an artifact
     - name: Upload Coverage Report
       uses: actions/upload-artifact@v4
       with:
         name: coverage-report
         path: coverage.txt
+
+  deploy:
+    runs-on: ubuntu-latest
+    needs: coverage
+    permissions:
+      contents: read
+      packages: write
+
+    steps:
+    - uses: actions/checkout@v4
+
+    # Set up the JDK environment
+    - name: Set up JDK 19
+      uses: actions/setup-java@v4
+      with:
+        java-version: '19'
+        distribution: 'temurin'
+        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
+        settings-path: ${{ github.workspace }} # location for the settings.xml file
+
+    # Download the coverage report from the previous job
+    - name: Download Coverage Report
+      uses: actions/download-artifact@v4
+      with:
+        name: coverage-report
+        path: coverage.txt
+
+    # Deploy Snapshot to GitHub Packages
+    - name: Deploy Snapshot to GitHub Packages
+      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/inestrivino/JavaPandas
+      env:
+        GITHUB_TOKEN: ${{ github.token }}
